AddMinimapAtlas("images/map_icons/bear_backpack.xml")
AddMinimapAtlas("images/map_icons/feather_backpack.xml")
AddMinimapAtlas("images/map_icons/valise.xml")
AddMinimapAtlas("images/map_icons/blood_sword.xml")
AddMinimapAtlas("images/map_icons/sherry.xml")
AddMinimapAtlas("images/map_icons/princess_cottage.xml")